# Generated by Django 3.0.7 on 2020-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заглавие')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=30, null=True, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
